### ISSUE TITLE
spelling

### ISSUE THREAD

**Issue by mestia** [FCS-analysis/PyScanFCS#11]
lintian in Debian complains about typos:

pyscanfcs: spelling-error-in-binary usr/lib/python2.7/dist-packages/pyscanfcs/SFCSnumeric.x86_64-linux-gnu.so occurences occurrences

pyscanfcs: spelling-error-in-binary usr/lib/python2.7/dist-packages/pyscanfcs/SFCSnumeric.x86_64-linux-gnu.so suports supports

**Comment by paulmueller** [comment]
Thanks for bringing this up. Is there any way to tell what exactly lintian complains about (I have no experience with it)? I assume this check is done against the latest development version?

**Comment by mestia** [comment]
This is really just a nitpicking from Lintian's side especially because the typos are in a lib and not in documentation where people will see them. Anyway because it is easy to fix, I decided to report it.

/tmp/PyScanFCS

```
grep -iR "occurences" .
./misc/binningc.pyx:    occurences = np.where(Data == 65535)[0]
./misc/binningc.pyx:    N = len(occurences)
./misc/binningc.pyx:    for i in occurences:
./misc/binningc.pyx:        zeroids[i*2] = occurences[i]+1
./misc/binningc.pyx:        zeroids[i*2+1] = occurences[i]+2
./pyscanfcs/SFCSnumeric.pyx:    occurences = np.where(Data == 65535)[0]
./pyscanfcs/SFCSnumeric.pyx:    N = len(occurences)
./pyscanfcs/SFCSnumeric.pyx:    datData[occurences] = np.uint32(Data[occurences+1]) + np.uint32(Data[occurences+2])*65536
./pyscanfcs/SFCSnumeric.pyx:    zeroids[::2] = occurences + 1
./pyscanfcs/SFCSnumeric.pyx:    zeroids[1::2] = occurences + 2

grep -iR "suports"
pyscanfcs/SFCSnumeric.pyx:        the file *filename*. *dlg* is a python object that suports 
```
