### ISSUE TITLE
pyscanfcs tests fail on some architectures

### ISSUE THREAD

**Issue by mestia** [FCS-analysis/PyScanFCS#17]
pyscanfcs tests fail on few architectures such as mips, ppc64, and s390.
My guess is that the failure is related to endianness - they all are big-endian as far as I see.
Any hint how to fix that?
Here is the build-log on [mips](https://buildd.debian.org/status/fetch.php?pkg=pyscanfcs&arch=mips&ver=0.3.0%2Bdfsg-1&stamp=1540819019&raw=0)

Thank you.
Alex

**Comment by paulmueller** [comment]
Could you please try again with the latest commit? If it fails again with an explicit endinness-error, I have another idea how to fix it.

**Comment by paulmueller** [comment]
I think this was caused by the fact that the code for opening these .dat file was (unnecessarily) part of a Cython module. I refactored the code (see commit above). Please try again.

**Comment by mestia** [comment]
Tests pass now. I've made the package from d295b59467cecfa6665eb162a30aea75826be5d4 and it works. [build on mips](https://buildd.debian.org/status/fetch.php?pkg=pyscanfcs&arch=mips&ver=0.3.1%7Egitd295b59%2Bds-1&stamp=1543529150&raw=0).
